fix: validate_string_identifier would allow some disallowed strings
codelabsab/rust-ocpp pull request #24
Opened 2023-08-16 06:37 UTC by Erk-

Any string containing at least one valid character would be allowed by the regex, this fix removes regex and does a normal scan of the string instead.

This patch also contains some cleaning in the Cargo.toml file where it removes dependencies that was not in use.

2023-08-21 17:09 UTC, tommymalmqvist commented
Hello again @Erk- sorry about the late response and thanks for the PR.

This is actually a remnant from when I had plans to implement a server and client in this repo and the file is not really used. I started writing a server in another repo.

Do you need it for something special?

2023-08-22 06:48 UTC, Erk- commented
I don't need it for anything, I was just looking through the dependencies and was seeing if I could remove some of them and spotted the issue above. So it may be better to just remove it.

2023-08-22 07:30 UTC, tommymalmqvist commented
Thanks I’ll remove it then!

2023-08-25 07:03 UTC, Erk- commented
@tommymalmqvist I can see that it is used for the `#[validate(...)]` attributes, should these also be removed or would it make more sense to keep `validate_string_identifier` in that case?

2023-08-25 09:20 UTC, tommymalmqvist commented
> @tommymalmqvist I can see that it is used for the `#[validate(...)]` attributes, should these also be removed or would it make more sense to keep `validate_string_identifier` in that case?

Yes, you are correct!

I could update the regex like so also:

```rust
let re = Regex::new(r"^[a-zA-Z0-9*+=:|@._-]*$").unwrap();
```

2023-08-25 10:41 UTC, Erk- commented
Yeah that would also be a valid solution, though it should probably be `..]+$`.

Would you rather keep a regex based solution because then I can switch to that.

2023-08-25 11:33 UTC, tommymalmqvist commented
Lets go with regex 👍

2023-08-28 12:16 UTC, Erk- commented
@tommymalmqvist I have updated it to use regex, so you can have another look now.

2023-08-29 08:03 UTC, tommymalmqvist requested changes

2023-08-29 08:03 UTC, tommymalmqvist commented on src/v2_0_1/helpers/validator.rs
> +        .get_or_init(|| Regex::new(r"^[a-zA-Z0-9*+=:|@._-]+$").unwrap())
The + symbol match the preceding character one or more times. In the specification the identifierString might be 0-n in length. I think we should use a * here instead.

For example in CostUpdatedRequest the specification of v2.0.1 states in the field type column: identifierString[0..36]

2023-08-29 10:52 UTC, tommymalmqvist approved these changes

2023-08-29 10:52 UTC, merged